# Generated by Django 4.1.10 on 2023-11-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("UID", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("pfp", models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("fID", models.AutoField(primary_key=True, serialize=False)),
                ("fName", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="file/")),
                ("fDateTime", models.DateTimeField()),
                (
                    "fUID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.user"
                    ),
                ),
            ],
        ),
    ]
